# Generated by Django 5.2.4 on 2025-07-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('place', models.TextField()),
                ('admin', models.TextField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('prepaid', 'Предоплата внесена'), ('paid', 'Оплачено'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('refunded', 'Возврат средств')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('full_name_client', models.CharField(max_length=255)),
                ('contact_client', models.CharField(max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('total_price', models.FloatField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.service')),
            ],
        ),
    ]
