# Generated by Django 5.2.4 on 2025-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_client',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('prepaid', 'Предоплата внесена'), ('paid', 'Оплачено'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('refunded', 'Возврат средств')], default='pending', max_length=20),
        ),
    ]
